### PR TITLE
Resize chart width on view resize

### PR DESCRIPTION
**Pull request by nbogojevic**
Here's one way to solve fit on resize (https://github.com/thegreystone/jmc-flame-view/issues/8).

The chart width is set to 90% of the view width and this is applied on every browser resize.

I've looked at height resize also, but it doesn't look as well when applied, so width resize seems sufficient.

### CODE REVIEW

**Comment by thegreystone** [comment]
Hi Nenad!

Great to see you here! 

I’m doing this with the intent of all of us together doing a contribution of this back to the OpenJDK JMC. To make that contribution easy, I am only accepting pull requests from people with a signed OCA.

Couldn’t find you on the OCA-list:
http://www.oracle.com/technetwork/community/oca-486395.html

See http://openjdk.java.net/contribute/ for more info on contributing to OpenJDK-projects.

**Comment by nbogojevic** [comment]
Sure thing, I've sent OCA yesterday - hope it will be processed soon.

**Comment by thegreystone** [comment]
Hi Nenad!

Your OCA has been checked by Dalibor and is now awaiting approval from Donald. Should not be long now!

**Comment by thegreystone** [comment]
Hi Nenad,

You're now listed on the OCA page (http://www.oracle.com/technetwork/community/oca-486395.html), so I think we're good to go!

**Comment by thegreystone** [comment]
Thank you for your contribution!

**Pull request merged**
